#!/bin/bash
#=================================================================================
# Configure an instance of Ubuntu 16.04 Desktop as a Java training environment.
#
# Version: 1.0.0
# Date: 07 Jun 2016
# Author: Dave Nicolette
#=================================================================================

clear
echo ' '
echo 'Provisioning this instance as a Java training environment'
echo 'setup script: version 1.0.0 01 Jun 2016'
echo 'Assumes Ubuntu 16.04 Desktop 64-bit'
echo ' '
echo 'Applying system software updates...'

# sudo apt update
# sudo apt -y dist-upgrade

# This could be true if the setup script was obtained from a source other than github

if [ ! -f /usr/bin/git ]; then
    echo ' '
    echo 'git is required and is not installed'
    echo 'intalling git...'
    sudo apt install -y git
fi

export INSTALL_DIR="$HOME/provision-ubuntu-16.04-javatrain"
export COMMON_DIR="provision-ubuntu-16.04-common"

# On a re-run of the setup script, this repo will already have been cloned

if [ ! -f "$COMMON_DIR" ]; then
    git clone "git://github.com/training/$COMMON_DIR"
fi

"./$COMMON_DIR/install_development_basics"
"./$COMMON_DIR/install_java_development_tools"

if [ ! -f "$HOME/Desktop/help.html" ]; then
    echo ' '
    echo "Copying help file to $HOME/Desktop"
    cp help.html "$HOME/Desktop/help.html"
fi
